axis_linear: 1
scale_linear: 0.08
#scale_linear_turbo: 1.60
#scale_linear_turbo: 0.8
scale_linear_turbo: 1.0
scale_angular: 0.2
scale_angular_turbo: 0.8

#axis_angular: 0
#scale_angular: 0.4
#scale_angular_turbo: 0.4

enable_button: 1
enable_turbo_button: 0
